### PR TITLE
Added modal styles

### LINKED ISSUE #1: A better looking react-modal on the browser i.e some css changes for react-modal so that it looks better.

### PR DESCRIPTION
**Pull request by ghosh**
It looks like this now.

screen shot 2017-10-02 at 6 38 30 pm

Closes #1

### CODE REVIEW

**Comment by MohitChattlani** [comment]
The modal looks great on the browser but it does not look good for smaller resolutions like mobile. Here is a look. Please make a view so that it has comfortable viewing for both smaller and bigger resolutions.
screenshot from 2017-10-02 21-25-57

**Comment by ghosh** [comment]
@MohitChattlani Good catch. Made it responsive.

**Comment by MohitChattlani** [comment]
let me check.

**Comment by MohitChattlani** [comment]
Looks great to me. @ghosh

**Pull request merged**
